### ISSUE TITLE
A question about DL framework

### ISSUE THREAD

**Issue by JSnobody** [Tencent/PocketFlow#10]
I find PocketFlow use Tensorflow.
Is there a strong correlation between your optimization and Tensorflow?
Does the optimization apply to other DL framework?
Why not use NCNN?
Look forward to your reply!
Thansk very much!

**Comment by jiaxiang-wu** [comment]
Sorry, I do not fully understand your question.
1. What do you mean by "optimization"?
2. Also, ncnn is a mobile-based inference library, while ours is a training framework for producing compressed models.

**Comment by JSnobody** [comment]
Such as channel pruning，weight sparsification，weight quantization，network distillation，multi-GPU training， hyper-parameter optimization.

**Comment by jiaxiang-wu** [comment]
TensorFlow is a framework for both training and inference, while ncnn is only for inference on mobile devices. That's why we choose TensorFlow instead of ncnn to implement these methods, since they are all training algorithms for model compression.

**Comment by 3dimensions** [comment]
Does PocketFlow's compression methods apply to other training frameworks like PyTorch or Keras? Why choose Tensorflow?

**Comment by jiaxiang-wu** [comment]
@3dimensions @JSnobody 
We choose TensorFlow since it is one of the most popular DL framework for the moment. It is possible to extend PocketFlow to other frameworks, e.g. PyTorch, but this will require lots of works. 
On the other hand, these model compression methods are not limited to TensorFlow. You surely can implement them using PyTorch or other DL frameworks.

**Comment by jiaxiang-wu** [comment]
Closing this issue. Reopen it if there are any further questions.
