### ISSUE TITLE
New weight sparse method

### ISSUE THREAD

**Issue by Maoquan232** [Tencent/PocketFlow#161]
Hi, I  want to add some other weight sparse method. It seems that I  need to create a new learner with the pr_optimizer, rl_helper.  I am confused about the relationship between them. 
Can you give some guidelines on how to add a new weight sparse method?

**Comment by jiaxiang-wu** [comment]
To start with, you only need to implement a `xxxxLearner` class which includes your weight sparsification method. If your algorithm involves some hyper-parameters that need to be automatically tuned via RL, then you may need "pr_optimizer" and "rl_helper". Otherwise, a single `xxxxLearner` class should be enough (*e.g.* `UniformQuantTfLearner` for uniform quantization based on TensorFlow's quantization-aware training APIs).
