### ISSUE TITLE
What's the minimal version

### ISSUE THREAD

**Issue by ysh329** [Tencent/PocketFlow#170]
Hi, all.

I wanna ask what's the minimal version. I found when executing pocketflow script, which generate a minimal version of pocketflow as below:

```shell
$ ls
PocketFlow  PocketFlow-minimal
```

Besides, I found the minimal version is really minimal as below:

```shell
$ du -sh ./*
2.7M	./PocketFlow
1.7M	./PocketFlow-minimal
```

And I found nothing in docs about this `PocketFlow-minimal`.

What's the difference between them? 🙇 

thanks in advance.

**Comment by jiaxiang-wu** [comment]
Basically, it removes logs and model files and all the git-related files (under the ".git" directory). All the code files are kept unchanged, so that the program should be able to run as expected.
The motivation for creating a minimal version of this directory is that in the docker (or seven) mode, we need to mount (or upload) the current directory and we want the directory to be as small as possible.

**Comment by ysh329** [comment]
@jiaxiang-wu Thanks your detailed explanation.
