### ISSUE TITLE
Whether need modify forward_fn function for each model before compression

### ISSUE THREAD

**Issue by ysh329** [Tencent/PocketFlow#183]
Hi, all,

I checked all [test cases in docs](https://pocketflow.github.io/test_cases/), and found all `forward_fn` are different for different model. Thus, I wanna know: 

1. if it's necessary to define `forward_fn` for user defined model(not from model zoo or `utils.external`)? (If model has many layers, it seems very complex to define the model)
2. If using user's model, how can I modify `forward_fn` function; how to define `inputs`, `is_train`, `data_format` parameters, etc.

Thanks in advance.

**Comment by jiaxiang-wu** [comment]
1. `forward_fn` is where you define the model's forward-pass computation. I think it is necessary to define this for user-defined models. Or, if you do not want to define `foward_fn`, can you provide other alternatives so that the user-defined model can be implemented and understood by learners? Your suggestions are highly welcomed.
2. `inputs` is the input tensor (or dict of tensors) that needs to be fed into the model's forward-pass computation (for CV tasks, `inputs` often denotes images); `is_train` indicates whether the model is in a training or evaluation graph (this matters if BN layers is used); `data_format` indicates which data format is used (NCHW or NHWC).

**Comment by ysh329** [comment]
Thanks your very detailed explanation.
