### ISSUE TITLE
The export compressed models takes more computation time than original models, Why?

### ISSUE THREAD

**Issue by wuyong139** [Tencent/PocketFlow#189]
First, I train the model by "full-precision":
./scripts/run_local.sh nets/resnet_at_cifar10_run.py
second,
./scripts/run_local.sh nets/resnet_at_cifar10_run.py --learner channel --cp_prune_option uniform --cp_uniform_preserve_ratio 0.5
./scripts/run_local.sh nets/resnet_at_cifar10_run.py --learner dis-chn-pruned --dcp_nb_stages 3
third,
python tools/conversion/export_chn_pruned_tflite_model.py --model_dir models_eval
python tools/conversion/export_chn_pruned_tflite_model.py --model_dir models_dcp_eval
python tools/conversion/export_chn_pruned_tflite_model.py --model_dir models_chn
I test the model by "*.pb":
python tools/benchmark/calc_inference_time.py --model_file models_eval/model_original.pb
python tools/benchmark/calc_inference_time.py --model_file models_dcp_eval/model_transformed.pb
python tools/benchmark/calc_inference_time.py --model_file models_chn/model_transformed.pb

The result is :
full-precision: size:1.2M, accuracy:92.013%, time:3.54ms.
dcp: size:674.2K, accuracy:90.68%, time:4.53ms.
channel:size:728K,accuracy:88%, time:5.78ms.

Is there any wrong with my test process?

**Comment by jiaxiang-wu** [comment]
The default setup for conversion to *.pb & *.tflite models are using 1x1 conv for graph editing and NHWC data format, so that the generated *.tflite model can be deploy on mobile devices. For speed-up the inference with *.pb model on GPU, you need to use tf.gather for graph editing and NCHW data format. You may refer to https://github.com/Tencent/PocketFlow/pull/119 for detailed explanation.

**Comment by wuyong139** [comment]
@jiaxiang-wu Thanks for your reply
