### ISSUE TITLE
Can you reshape the responding kernels after channel pruning, the convolutional cores is full of zero but can not reduce the computation in the tflite which i think could be completely removed

### ISSUE THREAD

**Issue by jiuyecao** [Tencent/PocketFlow#203]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jiaxiang-wu** [comment]
Directly reshaping the convolutional kernel after pruning is more complicated, since you need to consider all the BN/ReLU/Pooling layers before and after this convolutional layer, and adjust their input (or output) tensors' shape. We have not found out an elegant way to do so. If you have experience in this, we highly welcome your contribution, *e.g.* propose a pull request.
