### ISSUE TITLE
Is there any way to use both "channel prune" and "quantization" for a model?

### ISSUE THREAD

**Issue by huanyingjun** [Tencent/PocketFlow#262]
Hello, 
Is there any way to use both channel prune and quantization for a model?
I mean, first I prune model with "chn-pruned-rmt" learner, after this , I can quantize the prune model by "uniform-tf" learner ?

**Comment by jiaxiang-wu** [comment]
Currently not supported, since in all channel pruning based learners, the pruned channels are not actually removed since TensorFlow graph for *.ckpt models only allows appending nodes, instead of replacing or deleting nodes. One possible approach is to firstly convert *.ckpt model to *.pb model, remove pruned channels, and convert channel-pruned *.pb model back to *.ckpt model with training operations re-inserted, and then use "uniform-tf" learner for quantization-aware training.

**Comment by NJUIoT** [comment]
> Currently not supported, since in all channel pruning based learners, the pruned channels are not actually removed since TensorFlow graph for *.ckpt models only allows appending nodes, instead of replacing or deleting nodes. One possible approach is to firstly convert *.ckpt model to *.pb model, remove pruned channels, and convert channel-pruned *.pb model back to *.ckpt model with training operations re-inserted, and then use "uniform-tf" learner for quantization-aware training.

Hey, I notice that the implemented pruning process uses a mask to prune those redundant channels, so that the model size of checkpoint is the same as the original version. How the actual pruning process can be performed? Will Tensorflow remove those masked channels automatically during transforming the *.ckpt file to the *.pb file? I pruned two layers of VGG16 (between layer 1 and layer 4, only 2 and 3 are pruned, for example, the showing pruning ratio for layer 2 is about 0.6), but the model size does not change at all for the *.pb file. I wonder whether there is some details I missed out.
Thanks!

**Comment by uidp1499** [comment]
> Currently not supported, since in all channel pruning based learners, the pruned channels are not actually removed since TensorFlow graph for *.ckpt models only allows appending nodes, instead of replacing or deleting nodes. One possible approach is to firstly convert *.ckpt model to *.pb model, remove pruned channels, and convert channel-pruned *.pb model back to *.ckpt model with training operations re-inserted, and then use "uniform-tf" learner for quantization-aware training.

Do you have any user-guide or steps to follow to convert a pruned *.pb model to trainable *.ckpt file?
