### ISSUE TITLE
Model Pruning taking too much time to train

### ISSUE THREAD

**Issue by dhingratul** [Tencent/PocketFlow#60]
**Describe the bug**
Hi, I have been training the pruning script for last 3 days, as of now it has only generated a couple of checkpoints in model_dcp, but to generate the .tflite and .pb file, i need the model_dcp_eval , which i am assuming will be generated after the training has been "done". I want to just skip to the end, and evaluate the inference times of pruned vs non-pruned model. I dont care about accuracy at this point as much. If i freeze the graph from these checkpoints will it give me the pruned model, because in the documentation it says, "conversion script automatically detects which channels can be safely pruned, and then produces a light-weighted compressed model". I just need the pruned .pb file. 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jiaxiang-wu** [comment]
To export a TF-Lite model, you need checkpoint files of the evaluation graph (stored in "./models_dcp_eval"), instead of the training graph (stored in "./models_dcp"). If you want to use these checkpoint files of the training graph, you need to restore variables from them and save again as the evaluation graph (take a look at `DisChnPrunedLearner`'s implementation).

BTW, if you want to accelerate the training process and quickly evaluate the run-time speed comparison, and do not care much about the accuracy, you can set `--nb_epochs_rat` to some small value. This argument specifies how many training epochs will be used. For instance, if you set `--nb_epochs_rat` to 0.1, then only 10% training epochs will be used, compared with the standard setting, so that the training time will be 10 times faster.

**Comment by dhingratul** [comment]
Is there a way to resume the training from where it stopped, and pass that argument this time ?

**Comment by jiaxiang-wu** [comment]
Sorry, current `DisChnPrunedLearner`'s implementation does not support this. You need to modify its implementation to be able to recover from a previous run.

**Comment by dhingratul** [comment]
@jiaxiang-wu Does `--nb_epochs_rat` parameter also work with other optimizations such as uniform quantization ?

**Comment by dhingratul** [comment]
It should be added for all the optimizers. Also, how long does it take for Uniform Quantization to train on a single GPU(1080ti)

**Comment by jiaxiang-wu** [comment]
Basically, their performance (in accuracy) is similar, since the underlying training algorithm is the same, despite some implementation details. The native version, `UniformQuantLearner`, provides more features, including variable number of quantization bits for each layer (so that RL can be used to optimize the strategy), than the TF version, `UniformQuantLearnerTFLearner`. However, the latter can be exported to TF-Lite models and deployed on mobile devices, while the former cannot.
