### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by GeorgeKaspar** [Tencent/PocketFlow#7]
Could you please place pre-trained pruned models for standard architectures resnet18, mobilenetv1/2 etc...?

**Comment by jiaxiang-wu** [comment]
Hi, do you mean to provide multiple pre-trained pruned models for each network (ResNet-18 or MobileNet-v1/v2), one per overall pruning ratio (or acceleration ratio)?

**Comment by GeorgeKaspar** [comment]
Yes, it will be great!
I mean prune models from README

**Comment by jiaxiang-wu** [comment]
Since there are so many possible pruning ratios, and different people may have different target acceleration ratio, we think it is less meaningful to provide multiple pre-trained pruned models for each network. Still, it is possible that we provide one pre-trained pruned model for each network.
P.S.: If you have trained multiple pruned networks, we welcome you to share them with the community.

**Comment by GeorgeKaspar** [comment]
@jiaxiang-wu yes it will be great to provide few pretrained pruned models
