### ISSUE TITLE
How to use distill when compress

### ISSUE THREAD

**Issue by as754770178** [Tencent/PocketFlow#89]
If I want to compress the model by distilling, I must gave the pretrained model in `save_path_dst`?
The compressed model is new construct and changed, how to get the pretrained model of compressed model?

**Comment by jiaxiang-wu** [comment]
By default, the `DistillationHelper` class will download a pre-trained model via `wget`, and rewrite it into the directory specified by `FLAGS.save_path_dst` (with variables' name scope changed from "model" to "distilled_model"). If the pre-trained model is in-place, then you do not need to put anything into the directory specified by `FLAGS.save_path_dst`, since the above process is handled by `DistillationHelper`.
