### ISSUE TITLE
Resnet &  Dis-chn-pruned: Waiting for three hours.... No more INFO. Still Keep "Restoring parameters". 

### ISSUE THREAD

**Issue by jzlwlhao** [Tencent/PocketFlow#93]
Input Command: ./scripts/run_local.sh nets/resnet_at_ilsvrc12_run.py  --learner dis-chn-pruned
The last Info is Restoring parameters from ./models/model.ckpt-250227. 
This is found in the newest code for today's update.

Screen information:
INFO:tensorflow:model files: model.ckpt-250227.index, model.ckpt-250227.meta, checkpoint, model.ckpt-250227.data-00000-of-00001
2018-11-22 11:43:25.612239: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:layer-to-block mapping: [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3]
INFO:tensorflow:Restoring parameters from ./models/model.ckpt-250227

**Comment by jiaxiang-wu** [comment]
Thanks for the feedback. We are investigating this issue and will push a fix ASAP.

**Comment by jiaxiang-wu** [comment]
@jzlwlhao 
I've run the execution command you provided. The program is working as expected. Actually, the program is not stuck at restoring parameters. After parameters are restored, DCP learner starts the channels selection process, and the block-wise fine-tuning is time-consuming and does not output any log:
``` Python
# fine-tune the current block
for idx_iter in range(nb_iters_block):
if (idx_iter + 1) % FLAGS.summ_step != 0:
  self.sess_train.run(self.block_train_ops[idx_block])
else:
  summary, __ = self.sess_train.run([self.summary_op, self.block_train_ops[idx_block]])
  if self.is_primary_worker('global'):
	self.sm_writer.add_summary(summary, nb_iters_block * idx_block + idx_iter)
```

Since you are using only one GPU, this part can take very long. You may add some outputs in the above code to verify this.

**Comment by jiaxiang-wu** [comment]
@jzlwlhao Can you confirm whether your issue has been resolved?
